apiVersion: v1
kind: ConfigMap
metadata:
  name: app-kubecfg
  annotations:
    ves.io/virtual-sites: ${utility_namespace}/${utility_vsite}
data:
  kubeconfig: |
    ${app_kubecfg}
 
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: podcleaner
  annotations:
    ves.io/virtual-sites: ${utility_namespace}/${utility_vsite}
spec:
  schedule: "*/6 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            ves.io/workload-flavor: tiny
            ves.io/virtual-sites: ${utility_namespace}/${utility_vsite}
        spec:
          containers:
            - name: cleaner
              image: ${reg_server}/cleaner
              env:
                - name: NAMESPACE
                  value: ${app_namespace}
                - name: KUBE_PATH
                  value: /tmp/kubeconfig
              volumeMounts:
              - mountPath: /tmp
                readOnly: true
                name: kubecfg
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          volumes:
          - name: kubecfg
            configMap:
              name: app-kubecfg
              items:
                - key: kubeconfig
                  path: kubeconfig
          restartPolicy: OnFailure
          backoffLimit: 1
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          imagePullSecrets:
            - name: f5demos-registry-secret